### ISSUE TITLE
Generally all gd

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad21-practical-4---recyclerview-verrgod#2]
https://github.com/MAD11877/mad21-practical-4---recyclerview-verrgod/blob/3cc89197e6dcba04028e4c42d7573db4cdb790cf/app/src/main/java/sg/edu/np/mad/practical2/UsersAdapter.java#L45

Good job on discovering this method. 
But did you realise both your if block and else block have exactly the same codes, except the 2 TextViews' ID. 
This is the beauty of RecyclerView, you have have both layout files with exactly the same IDs. When you swap one layout with another, findViewById will only find the one that is currently visible and applicable in that context. So you do not need duplicated code blocks to handle the same views of different layout files.

https://github.com/MAD11877/mad21-practical-4---recyclerview-verrgod/blob/3cc89197e6dcba04028e4c42d7573db4cdb790cf/app/src/main/res/layout/activity_main2.xml#L11

Your width of RV is fixed, while the height is warp_content. A little risky here if the RV has arraylist that is not fixed size (e.g. chat messages), Android might not be able to render the RV correctly.

**Comment by verrgod** [comment]
Understood. Issues should be fixed.
